"""empty message

Revision ID: e3aae288a364
Revises: ffb53dc62ead
Create Date: 2024-02-26 11:32:08.878837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3aae288a364'
down_revision = 'ffb53dc62ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_recipes',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_categories_recipes_category_id_categories')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_categories_recipes_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('category_id', 'recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories_recipes')
    # ### end Alembic commands ###
